# -*- coding: utf-8 -*-
"""PRODIGY_GAI_01_GPT2_Text_Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cnIVGtHxi9TIhaDasAWkJQrjrNAuEM_
"""

!pip install transformers datasets torch

training_text = """
Artificial Intelligence is transforming industries.
Machine Learning helps computers learn from data.
Generative AI can create text, images, and code.
AI is becoming an important technology in modern life.
Deep Learning uses neural networks to solve complex problems.
"""

with open("training_data.txt", "w") as f:
    f.write(training_text)

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="gpt2"
)

prompt = "Artificial Intelligence"

result = generator(
    prompt,
    max_length=100,
    num_return_sequences=1
)

print(result[0]["generated_text"])